[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter = { command = "rustfmt" }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettierd" }
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettierd" }
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "nix"
formatter = { command = "nixpkgs-fmt" }
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "python"
language-servers = ["basedpyright"]
formatter = { command = "black", args = ["-q", "-"] }
indent = { tab-width = 4, unit = "    " }
auto-format = true
