setw -g mode-keys vi
set -s escape-time

# Set default terminal inside tmux to support 256 colors
set -g default-terminal "tmux-256color"

# Inform tmux that your outside terminal supports True Color (RGB)
set -as terminal-features ",xterm-256color:RGB"
